### ISSUE TITLE
No bounding boxes drawn on iOS

### ISSUE THREAD

**Issue by codscino** [ferraridamiano/yolo_flutter#4]
I am running the example package with yolov8n and this photo(https://www.pexels.com/photo/brown-tabby-cat-2071882/) on iOS simulator iPhone 14 iOS 17 and no bounding boxed is drawn even if in the terminal it says :  NMS time: 14 ms, Detected 1 bboxes.

There was another error about photo permission, I just added this in the iOS/Runner/Info.plist file:
`<key>NSPhotoLibraryUsageDescription</key>
    <string>We require access to your photo library to enable photo selection within the app.</string>`

I have the same problem with a physical iPhone 11.

**Comment by ferraridamiano** [comment]
Are you using the latest version of this code and the latest version of ultralytics? Because recently there was a change about the output format of the model and the output needed to be scaled up. Could you try printing the detected bounding box?

**Comment by codscino** [comment]
Yes I am using last version of your code and ultralytics, I have generated the model with this python script:
`from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')  # load an official model

# Export the model
model.export(format='tflite')`


I got to models: yolov8n_float16.tflite, yolov8n_float32.tflite. I put the float32 in the assets/models folder and I renamed it yolov8n.tflite.

I added to home_page.dart another debugprint:
`debugPrint('Detected ${bboxes.first}');`

And I got this:

`Detected [535.5945888519287, 846.0391759872437, 921.109838104248, 1312.670373916626, 0.0001931501756189391, 0.000020750530893565156, 0.00000545352122571785, 0.000002501122480680351, 0.0000021792043298773933, 7.737016858300194e-7, 0.0000012389774610710447, 9.56103249905027e-8, 2.909093836933607e-7, 0.000004615243142325198, 0.000007136276963137789, 0.000005957605026196688, 0.00000458114027424017, 0.000029978993552504107, 0.0038761773612350225, 0.7701735496520996, 0.009342959150671959, 0.0006671288283541799, 0.00032755776192061603, 0.0001866855309344828, 0.00011910011380678043, 0.004815025720745325, 0.00034990347921848297, 0.0020033963955938816, 0.00004043157969135791, 0.00022256889496929944, 0.00009807602327782661, 0.000018544087652117014, 0.00016369290824513882, 0.0000030387118385988288, 0.0000010626005177982734, 3.2828754115143965e-7, 0.000010484812264621723, 7.153626597755647e-7, 1.70493933637772e-7, 0.0000012640369959626696, 0.0000012408670500008157, 8.098925832200621e-7, 0.000014372<…>`

**Comment by ferraridamiano** [comment]
How to interpret this data? The first 4 cells refer respectively to the x, y, width, and height of the bounding box. But they are scaled, it would be more interesting to see the normalized version, you can print the bboxes variables after the nms operation inside the postprocess function in the yolo.dart file. The other 80 cells refer to the class probabilities. In your case the class with more probabilities is on cells 19, you have to subtract 3 (because the first cells are for the bbox position and size) and you get 16 which corresponds to the cat which is right (see the labels.dart file).

That said, I'm not sure why it's not showing the bounding box, maybe it is because it is larger than the image itself, could you try printing the normalized version of the bounding box as suggested above? Does this happen just with this image or also with all the images?

**Comment by ferraridamiano** [comment]
Closing. I did not receive any answers after 7 months, I suppose it is resolved
